service: event-bridge-serverless
provider:
  name: aws
  runtime: nodejs10.x

  region: ap-south-1
  stage: dev

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - events:*
        - lambda:AddPermission
        - lambda:RemovePermission
      Resource: "*"

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  bob:
    handler: handler.bob
    # events:
    #   - eventBridge:
    #       schedule: rate(1 minutes)
  bobEnd:
    handler: handler.bobEnd
  alice:
    handler: handler.alice
    events:
      - http:
          method: GET
          path: alice/{ruleName}/{duration}/{startAt}
          cors: true
          request:
            parameters:
              paths:
                ruleName: true 
                duration: true
                startAt: true
                
          

